### ISSUE TITLE
TOB | Stability investigation - document app startup for restart, backup and recover-ability

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#268]
Investigate the start up process across repos and document the findings.

**Comment by swcurran** [comment]
Findings from Wade:

My notes from the discussions today; a scenario.

- An issuer service starts up for the first time.
- Key pairs (preferably random) are generated and written to the wallet. These need to be backed up somewhere so they can be recovered should the wallet become corrupt or have to be forcefully reset.
- The service starts registering schemas with a ledger, and initializing it's wallet with corresponding information.
- The service needs to be able to recover from a condition where data has been written to the ledger but the corresponding information was not written to the wallet (or the wallet was forcefully reset). It is not practical to reset a production ledger.
- Once a wallet contains the information necessary for day to day operation, it needs to be backed up so it can be recovered should it become corrupt or lost.

**Comment by swcurran** [comment]
In development mode, where we are using an existing ledger, but starting up a new wallet, we can recreate the key pairs associated with a DID by using a known seed, but there is a keypair created with a Cred Def and that *cannot* be recreated - we don't control the seed. As such, wallets of issuers cannot be recreated.

We could implement (and the HL Indy team is planning to implement) backup/restore functions that could be used to preserve a wallet across invocations.

**Comment by swcurran** [comment]
@wade - re the issue 

```
The service needs to be able to recover from a condition where data has been written to the ledger but the corresponding information was not written to the wallet (or the wallet was forcefully reset). It is not practical to reset a production ledger.
```

This is only an issue with ledger entries that have keypairs - AFAIK, only DIDs and Cred Defs.  E.g. this is not a problem with a Schema written to the Ledger.  Not certain, but I think the wallet is written first, so the scenario you mention may not come up at all.  Even if it can't, the reverse could come up, and we should take care of that - having something in the wallet that is not yet on the ledger.

If I'm not right and the sequence is:

1. Generate keypair
2. Write to Ledger
3. Write to Wallet

To avoid the problem you identify, the keypair would have to be persisted across invocations to be sure that it eventually go to the wallet.  We'd need a place to stash that.

I don't think that Indy-SDK enforces ordering of operations related to the ledger. It just gives you the primitives to do operations, so I think we can do the ordering in the way that works best for us (e.g. generate key, write wallet, write ledger).

**Comment by sklump** [comment]
The sdk generates keys inside the wallet and only ever exposes the public key, by design. The sovrin design goal has always been privacy, not confidentiality: private keys are not available, ever.

In my opinion, the most seamless way to manage private key backup for those keys in wallets is to back up the underlying file system, and/or RAID.

**Comment by darrellodonnell** [comment]
Can the binary of the wallet be backed up and restored elsewhere?

As far as RAID I don't suggest that as a backup approach. It is good for resilience but doesn't protect from the most common human errors.

**Comment by sklump** [comment]
It's a file by default, or a database for an Enterprise wallet, so sure it could be backed up unless I've missed the obvious.

**Comment by ianco** [comment]
It's a SQLite database (actually SQLCrypt) for the default wallet and currently Postgres for he Enterprise Wallet.  Both can be backed up/restored by normal database mechanisms.  The discussion last Thursday also proposed standard import/export formats for interoperability (backup from SQLite and restore to Postgres, for example, if upgrading to an EW).

**Comment by swcurran** [comment]
In Indy-SDK - the DID key pairs can have an optional seed so that they are reproducible, but there is no providing a key for a Cred Def key pair, so it cannot be recreated.  IMHO, this is an error that should be fixed in the Indy-SDK, since it makes using seeds for everything else of limited value.

As @ianco mentioned, in the talk about the new wallet design that supports tags, there is talk of providing a managed export/import mechanism for a wallet.  I think this is important so that:

* The implementation is safe - e.g. that the export is safely encrypted in a consistent way (not left to each developer to define their own approach)
* For production backup/restore (independent of database-specific mechanisms).
* For upgrading wallets (convert from one database manager to another).
* For test suite management usage - import during initialization, delete at teardown

However, there is no reason not to use database-specific backup mechanisms.
