### ISSUE TITLE
Define an initial set of methods for updating the TOB Search Database based on incoming Credentials

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#276]

**Comment by nrempel** [comment]
Also, @ianco recommended a couple libraries we could lean on for json manipulation.

https://github.com/Onyo/jsonbender looks quite attractive. I'm going to do some more research but I'm thinking that, if this library is flexible enough, we can have each region register their own transformers for each credential type and map the data directly onto a Django model.

**Comment by swcurran** [comment]
@nrempel - I don't quite see why that is needed, but you would know better.  Remember that the TOB Data Model will be locked down, and the inputs will always be a flt list of name value pairs.  With those two constraints, I would think that a declarative model would be possible, which would be preferred.

**Comment by nrempel** [comment]
I know the TOB database will be locked down, but what about the incoming credentials?

I was under the impression those would evolve over time and that the format would be different for each region. i.e., A different mapper would be needed for each region.

**Comment by cywolf** [comment]
@nrempel Maybe `models` should be a list to allow multiple addresses and names?

I think having the choice of something like `from-claim` and `from-value` (maybe even `from-helper`) would also be a lot less verbose than using a processor for those cases, although the processors sound useful in general.

**Comment by nrempel** [comment]
It could be a list, but I can't think of a use case where a single credential maps to multiple addresses. But I suppose it never hurts to be more flexible.

Yeah, I agree the format currently is pretty verbose, but I wanted the ability to have an arbitrary pipeline of processors. e.g., input("key")->getFromCredential["key"]->toISO8601->etc

Also, it's verbose but the registration is only done once, so it shouldn't be too big of a burden on any workflows

**Comment by nrempel** [comment]
Based on @cywolf's feedback, I've come up with the following format for as much flexibility as possible. Yet, the most common cases (getting value from claim or sending string literal) are less verbose. A data processing pipeline is still supported.

```json
{
    "issuer": {
        "did": "abc123",
        "name": "bcreg",
        "abbreviation": "BCR",
        "email": "bcreg@bc.ca",
        "url": "reg.bc.ca"
    },
    "jurisdiction": {
        "name": "BC Registries",
        "abbreviation": "BCR"
    },
    "credential-types": {
        "name": "Registration",
        "schema": "registration.bc_registries",
        "version": "0.0.1",
        "endpoint": null,
        "mapping": {
            "src-id-key": "org_registry_ID",
            "models": [
                {
                    // Model names are validated
                    "model-name": "Name",
                    // Each field in model required (defined by TOB)
                    "fields": {
                        "name": {
                            "from-claim": "org_name"
                        },
                        "language_code": {
                            "from-value": "en"
                        }
                    }
                },
                {
                    "model-name": "Person",
                    "fields": {
                        "full_name": {
                            "from-claim": "owner_name"
                        },
                        "name_type": {
                            "from-value": "good"
                        },
                        "start_date": {
                            "processor": {
                                // staticly define the key to use
                                "input": "effective_date",
                                "steps": [
                                    // Look it up in the claim by key
                                    "fromClaim",
                                    // pipe to function
                                    "iso8601ToEpoch"
                                ]
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

At registration time, TOB will enforce that a mapping can include only one of `from-claim`, `from-value`, `processor`.
