### ISSUE TITLE
Upgrade TOB to use the new VON-Image based on VON-Agent 1.0.0

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#281]

**Comment by WadeBarnes** [comment]
TOB is now using the `von-image` (currently `py36-indy1.3.1-dev-441-ew`) as the base.

**Comment by WadeBarnes** [comment]
I've updated the build configuration for the `python-libindy` build which builds the s2i base image for the tob-api to allow the Docker file to manage the `von-image` version it uses.  That way we just update the one file when we want to use a different version of `von-image`.

I've added a pipeline with web-hook so the build will get kicked off when changes are made to any of the files related to the `python-libindy` image.

The changes have been rolled out to the BC and Ontario tools spaces.

**Comment by WadeBarnes** [comment]
@cywolf, Over to you.  Let me know if there is anything I can help with.

**Comment by cywolf** [comment]
py36-indy1.3.1-dev-441-ew-django-s2i

Maybe I should define some alternate version numbers..

**Comment by WadeBarnes** [comment]
Opened a PR for migrating the s2i build and scripts; https://github.com/PSPC-SPAC-buyandsell/von-image/pull/2

**Comment by WadeBarnes** [comment]
We've migrated over to the new von-image s2i image for the tob-api builds.  All of the python-libindy related files have been removed.

Switching tob-api to build off a different image/tag is now managed thought the `django` build configurations a `django-build*.param` files.
