### ISSUE TITLE
Create an extensible mechanism for managing Configuration Flags for tuning different instances of TOB

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#283]
Enable a "permissions"-like, extensible set of configuration flags for TOB that allows different underlying behaviour for different instances of TOB - for example, BC and Ontario instances.

Example requirements:

* Configure the Web API such that in some cases only the Municipal component of the address is returned (city or town) and in other cases, the full address is returned. In parallel, enable the frontend to present the data received appropriately - e.g. hide the labels for the Address fields not included.
* Configure Web API search such that, for some TOB instances, when a Name search is done, Legal Names and DBAs are returned as separate, unlinked entities, while in other instances, Legal Names and DBAs are returned as a single entity.

Make sure that settings are available to all components of TOB - especially the server and frontend - so that the desired behaviour is applied consistently across all components. For example, the settings could be instantiated in the Server and made available to the frontend via an API call.

**Comment by WadeBarnes** [comment]
Quick update.  @mitovskaol and I had a discussion on Wednesday and came up with a plan.  She is running with the idea as a first iteration while filtering the data for the Ontario profile.

The configuration is defined in the TOB setting module and structured in a json graph, the `instance` configuration is identified by an environment variable.  We also plan to expose an API to allow connected services (for each the UI) to retrieve the same configuration settings used by the server instance.

**Comment by mitovskaol** [comment]
After the discussion with Wade, Stephen, Nick and Ivan, the following approach has been accepted:

 - Whenever there is a customization required to exclude certain fields from the output, the code will be refactored to return a minimum set of fields by default and all additional fields will be returned if there is a custom configuration setting in effect that enables including the additional fields in the output. 

The following four areas in the TOB code have been identified that will need to be updated to implement the new feature:
 - Django Configuration File - settings.py - will import a custom settings.py that is specific for the each instance of TOB (Ontario vs BC). The custom settings.py contains a list of fields that should be exposed in this TOB instance IN ADDITION to the default set of fields.
 - Django Serializers - a serializer for the entity that contains the fields that are included in the custom settings configuration. The serializer will read the configuration from the custom settings.py and will build the output field set accordingly.
 - Search API - Search API endpoint(s) that expose the impacted fields will either need to be turned off or the Solr configuration need to be changed to exclude the "hidden" fields from the search.
 - Claims data - at this moment claimsJSON field in the VERIFIABLE_CLAIM  database table contain value for ALL fields included in the schema definition and this field can be queried through the API.  Need to think how to exclude certain fields from the output.

**Comment by swcurran** [comment]
@mitovskaol - I agree with the review from the meeting except for the last bullet about the Claims Data.  That API endpoint will either be eliminated (most likely) or at minimum will be protected from use externally.   Access to data in the Claims table would not be generically available (e.g. no /api/claims api call) - but could be accessed by a cross-table query underlying an API endpoint (e.g. one that picked up "status" for a credential).

Also missing is that the Credential page "Verify" button Proof Request would need to be customized to ensure that only relevant fields are included.  My expectation is that the Issuer would optionally provide a "Verify Button Proof Request" data structure that would be used for a Credential. If not supplied, the Proof Request would be generated as it is today, with all fields included.

**Comment by WadeBarnes** [comment]
The changes have been reviewed and merged.  Deployment configurations have been updated in DEV and TEST for the BC and Ontario TOB instances.

**Comment by WadeBarnes** [comment]
The changes have been deployed and smoke tested.
  - The `.../api/v1/settings` API returns the expected content.
  - The Location models contain only the fields listed in the settings.
