### ISSUE TITLE
Update the TOB Data Model based on agreed to design

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#291]
Update the TOB Data Model based on the design in this [Google Doc](https://docs.google.com/document/d/1UJujCVVlGnvDaE4eOVZM2Lwk2Lnbj9WikC9kB7AifUQ/edit#).  As necessary, evolve the design and if notify/consult the team if the changes are significant.

Note that the "set of credentials" fields needs to be expanded into a one-to-many join table so that a (for example) a "Name" row can be linked to many rows in the "Credential" table.

Care should be taken in rolling this out to prevent breaking the Test instance of TOB.  Perhaps doing this with a feature flag could be used to keep the branches short lived and we can run with old and new at the same time.  Obviously, we can manage the transition - we don't have a 24x7 uptime requirement - but we don't want to have it be a month where this lives in a non-merged branch.

**Comment by nrempel** [comment]
First cut of the data model update has been published. This will no doubt continue to be extended and modified as we implement features and discover new requirements.

![Screenshot 2018-05-08 16.07.21.png](https://images.zenhubusercontent.com/5ae8a5ee4b5806bc2bd15a54/bd08a4c8-8578-4fe7-8933-3ea12947d925)

**Comment by nrempel** [comment]
Since these changes are quite drastic, I'm taking the following approach to updating the data model and API:

1. Create new data model and update database schema without modifying existing schema *(done)*
2. Create a new /v2/ API without removing /v1/ routes
3. Code will be duplicated/refactored as needed for /v2/
4. /v1/ is deprecated and we can remove routes and code once services have moved over

**Comment by nrempel** [comment]
I've just learned that the new `von-agent` that will be used in v2 has breaking changes so we would need to something like:

- Update to new `von-agent` and add compatibility shims in the existing /v1/ code
- Keep around a `von-agent-legacy` copy of von-agent to be used in /v1/
- Update all services in unison and deploy all at once

I will think about the approach and discuss with others tomorrow.

**Comment by WadeBarnes** [comment]
Schema changes were deployed to DEV, and the Schema Spy documentation was updated automatically.

https://schema-spy-devex-von-dev.pathfinder.gov.bc.ca/
