### ISSUE TITLE
TOB V2

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#292]
As the data model is revised (Issue #25) revise the API. 

As with the TOB DB Model change, care must be taken to not break the existing Test, nor to have a long lived dev branch while this is done.  Perhaps a v2 api could be used?

A big part of this API revision is the elimination of many of the current API endpoints - there are WAY too many.  NTH would be a monitor for API usage so that we could see current traffic on all endpoints so that we can easily the see the ones not being used at all (and just eliminate them), see the ones that we want to eliminate but are being used (get the callers to change). If we could add this as a permanent feature, future API updates could be made much easier.

We do want to retain a Swagger definition of the API.

**Comment by nrempel** [comment]
I think publishing a v2 of the API is the right approach here.

We can maintain both versions until all services have moved over to the new API.

**Comment by swcurran** [comment]
In talking about the data model and UI implications we think that it would be probably be a good idea to re-add to the "Name" table the "srcId" field - the ID in the source system (e.g. BC Registries or OnBis) of the "Name" to better handle instances where there is a source system ID field associated with a DBA as well as with the Subject/Legal Name.   Let me know if this should be added as a separate issue.
