### ISSUE TITLE
Elaborate on the design of the Credential Processor

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#293]
We have a basic starting point for the design in the [TOB Data Model document](https://docs.google.com/document/d/1UJujCVVlGnvDaE4eOVZM2Lwk2Lnbj9WikC9kB7AifUQ/edit#). Expand on the design and do a technical spike on how it could work.  This should include:

1. How Issuers would define their mappings.
2. Some methods/mechanisms to process the existing Credentials we are currently processing.

**Comment by nrempel** [comment]
I propose that we extend the Issuer registration to include data mappings for every claim type that it registers with TheOrgBook.

```json
"mapping": {
            "src-id-key": "org_registry_ID",
            "models": [
                {
                    // Model names are validated
                    "model-name": "Name",
                    // Each field in model required (defined by TOB)
                    "fields": {
                        "name": {
                            "from-claim": "org_name"
                        },
                        "language_code": {
                            "from-value": "en"
                        }
                    }
                },
                {
                    "model-name": "Person",
                    "fields": {
                        "full_name": {
                            "from-claim": "owner_name"
                        },
                        "name_type": {
                            "from-value": "good"
                        },
                        "start_date": {
                            "processor": {
                                // staticly define the key to use
                                "input": "effective_date",
                                "steps": [
                                    // Look it up in the claim by key
                                    "fromClaim",
                                    // pipe to function
                                    "iso8601ToEpoch"
                                ]
                            }
                        }
                    }
                }
            ]
        }
```

There is some additional conversation on the topic of configuration format here: https://app.zenhub.com/workspace/o/bcgov/theorgbook/issues/276

Currently, the credential processor processes credentials with a fixed set of rules. We can update/refactor the credential processor class and surrounding utilities to process incoming credentials based on rules that have been submitted to TheOrgBook at registration-time.

I am planning to keep all existing code and workflows unchanged and publishing an entirely new v2 of the API. The supporting data model will live alongside the old model until all services can be moved over to use the new workflow.
