### ISSUE TITLE
Update Issuer registration step to save mapping configuration

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#298]

**Comment by nrempel** [comment]
```
{
    "issuer": {
        "did": "abc123",
        "name": "bcreg",
        "abbreviation": "BCR",
        "email": "bcreg@bc.ca",
        "url": "reg.bc.ca"
    },
    "jurisdiction": {
        "name": "BC Registries",
        "abbreviation": "BCR"
    },
    "credential-types": {
        "name": "Registration",
        "schema": "registration.bc_registries",
        "version": "0.0.1",
        "endpoint": null,
        "mapping": {
            "src-id-key": "org_registry_ID",
            "models": [
                {
                    // Model names are validated
                    "model-name": "Name",
                    // Each field in model required (defined by TOB)
                    "fields": {
                        "name": {
                            "from-claim": "org_name"
                        },
                        "language_code": {
                            "from-value": "en"
                        }
                    }
                },
                {
                    "model-name": "Person",
                    "fields": {
                        "full_name": {
                            "from-claim": "owner_name"
                        },
                        "name_type": {
                            "from-value": "good"
                        },
                        "start_date": {
                            "processor": {
                                // staticly define the key to use
                                "input": "effective_date",
                                "steps": [
                                    // Look it up in the claim by key
                                    "fromClaim",
                                    // pipe to function
                                    "iso8601ToEpoch"
                                ]
                            }
                        }
                    }
                }
            ]
        }
    }
}
```

**Comment by nrempel** [comment]
This is what I have now for the new issuer registration payload.

```
    {
            "issuer": {
                "did": "issuer DID",
                "name": "issuer name (english)",
                "abbreviation": "issuer TLA (english)",
                "email": "administrator email",
                "url": "url for issuer details"
            },
            "jurisdiction": {
                "name": "name of jurisdiction (english)",
                "abbreviation": "jurisdiction TLA (english)"
            },
            "credential-types": [
                {
                    "name": "claim type name (english)",
                    "endpoint": "url for issuing claims",
                    "schema": "schema name",
                    "version": "schema version",
                    "mapping": {
                        "src-id-key": "org_registry_ID",
                        "models": [
                            {
                                // Model names are validated
                                "name": "Name",
                                // Each field in model required (defined by TOB)
                                "fields": {
                                    "name": {
                                        "from": "claim",
                                        "input": "org_name"
                                    },
                                    "language_code": {
                                        "from": "value",
                                        "input": "en"
                                    }
                                }
                            },
                            {
                                "name": "Person",
                                "fields": {
                                    "full_name": {
                                        "from": "claim",
                                        "input": "org_name"
                                    },
                                    "name_type": {
                                        "from": "value",
                                        "input": "good"
                                    },
                                    "start_date": {
                                        "from": "claim",
                                        "input": "effective_date",
                                        "processor": [
                                            "parseDate"
                                        ]
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        }
```

**Comment by nrempel** [comment]
Let me know if you have any input @swcurran @cywolf @ianco

**Comment by swcurran** [comment]
Proposal for duplicates:

Name - name, language, NameType
Address - Addressee, CivicAddress, City, Province, PostalCode, Country, AddressType
Contact - Contact, ContactType
Person - FullName, PersonType

In going through this, I see that a tricky part of this approach is when to end date a record.  I think there is going to have to be a concept of "If <condition> then end date" - and I'm not sure of the scope of the <condition> - just the data coming in or the data and existing record.   I think we need some examples from Ian's world to see how we might approach that.  So - not needed immediately, but eventually.

**Comment by nrempel** [comment]
Ok that looks good, I'll move forward with those constraints and we can always iterate on that.

Just something to think about - is there a way to deterministically normalize all addresses? We might end up with duplicates like "UNIT 301, 797 TYEE RD" and "301-797 Tyee Rd."

I'll leave end_date as is for now and we can talk about it with some concrete data from Ian's system. It might be something that we can delegate to the event processor if it has more context.

**Comment by swcurran** [comment]
To clarify - the duplicates must also include SubjectID. 

Three solutions on the address duplicates.

* That's up to the issuer.  Not our problem :-)
* Normalize helper functions can be used and invoked by the issuer.
* We should use the geocoder (where possible - e.g. BC Addresses) for addresses to get Lat,Long and we can use the Lat, Long as the duplication indicator.  In that case - we do an update on the data, but don't replace the data.

What do you think of the last one?  I think we need a latlong field in the address table regardless. Should be there no matter what.

**Comment by nrempel** [comment]
All records are implicitly related back to a subject model with a subject (source) id – is that what you mean? I'll add an up-to-date physical model in this thread once I add the constraints.

Options 1 and 2 go together I think. Definitely the easiest path, but might lead to dirty data – but does that matter?

Option 3 is interesting. In that case, we would have a composite index on lat/lon and the contents of the address field wouldn't matter. We could have an out-of-band process to update and normalize those (api calls in cron job or by hand).

The question there is how fast can we pull a lat/lon from an address? If database writes are constrained by a call to an API, that would be a bottleneck. If we could download a database of address data -> lat/lon and run the query locally that could work. In that case, we could run a cron to update the geocoder db nightly or something.

I used a geocoder service a while back. I'll try and find the service. In the meantime, I'll add lat/lon to the schema regardless.

**Comment by nrempel** [comment]
Or we could normalize a postal/zip code easily and have a unique key only on that.

**Comment by swcurran** [comment]
Re: Subject ID - that comment was just to explicitly make sure that we weren't sharing addresses across SubjectIDs.

Re: Option 1+2 dirty data.  No, I don't think we care about the dirty data. If they do, they can deal with it.  In the future we might provide a cleaning service, but not until it's found to be needed.

Re: Option 3 - I think we have to add latlong to the model.  We need to add a helper function for the BC Gov geocoder to see about performance.  We may need to make that a background process to fill those in - which means that it won't help as an "on arrival concatenated key".

**Comment by swcurran** [comment]
LatLong is needed so that we can do spatial queries - "find me the businesses with a Liquor License within 5k of this address"

**Comment by swcurran** [comment]
A few questions/concerns:

* there should not be a unique constraint on country_code/postal_codes.  There can be many addresses with the same country/postal code.
* I thought that lat_long should be a single field.  Worth checking what common lat/long-based services use.
* We don't ever want data from one subject to share (join with) a row with another subject.  So we would never want two subjects to share an address (or name, person or contact).  At minimum - the start/end dates require that the address (et al.) be for a specific subject.  An example is that a Lawyer could be a person and address related to many Subjects and each will have different start/end dates.  In other words, we aren't trying to go third normal and minimizing data size.
* I think we agreed that we don't need an "initial_credential_id", as I (at least) don't think it really makes sense.  I don't think anyone else weighed in on whether it is good or bad.
* I recall that name needs a "source_id" field, so that we can link it back to either it's subject ID or DBA id.
* We need an "isLegalName" field in the "Name" table that will (usually - up to the Issuer) be set True or False in the mapping based on whether the source record is an Incorporation or DBA.

**Comment by nrempel** [comment]
Ok!

As per our discussion I've added some fields to name and ripped out lat/long for now.

Issuers can now also specify `cardinality_fields` in the registration. This is an array of values that inform the org book how to handle duplicates. The org book will attempt to retrieve and update an existing Address/Name/Contact/Person where every field in `cardinality_fields` is equal to the result of the matching `field` after the value runs through the pipeline. It also matches on the `subject` of this context and by null `end_date`s (it never updates records with an end date)

```json
{
    "issuer": {
        "did": "issuer DID",
        "name": "issuer name (english)",
        "abbreviation": "issuer TLA (english)",
        "email": "administrator email",
        "url": "url for issuer details"
    },
    "credential_types": [
        {
            "schema": "schema name",
            "version": "schema version",
            "description": "schema display name (english)",
            "endpoint": "url for issuing claims",
            "source_claim": "name of claim to obtain source_id from",
            "mapping": [
                {
                    "model": "address",
                    "cardinality_fields": [
                        "type"
                     ],
                    "fields": {
                        "addressee": {
                            "input": "addressee",
                            "from": "claim"
                        },
                        "civic_address": {
                            "input": "address_line_1",
                            "from": "claim"
                        },
                        "city": {
                            "input": "city",
                            "from": "claim"
                        },
                        "province": {
                            "input": "province",
                            "from": "claim"
                        },
                        "postal_code": {
                            "input": "postal_code",
                            "from": "claim"
                        },
                        "country": {
                            "input": "country",
                            "from": "claim"
                        },
                        "type": {
                            "input": "type",
                            "from": "claim"
                        },
                        "end_date": {
                            "input": "end_date",
                            "from": "claim"
                        }
                    }
                }
            ]
        }
    ]
}
```

For an issuer to 'end_date' a record, it sends a new credential that includes an end_date. Then, any future credential for that subject and cardinality_fields will be considered new.

The only caveat here is that if the issuer changes it's registration's `cardinality_fields`, it's possible to leave orphaned records without an `end_date`.

If the cardinality restrictions become more specific, then future credentials will not consider some records and they will never receive an `end_date`.

If the restrictions become less specific, then a query for an existing model could return multiple records. In this case, currently, we retrieve the most recently created record and update it. All other records are implicitly given an end date of 'now'.

I'm not sure there's much we can do to get around this caveat since we give the issuer services so much control.

@swcurran do you think this caveat is worth worrying about at this point? Do you think there is a better way to handle that scenario?

I'm now working on documentation for this model.
