### ISSUE TITLE
Load test the Issuer/Holder Process between a VON-X implementation and TOB

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#306]
We've run a number of Issuer/Holder load tests - permitify first issued credentials at TOB and TOB processes them for storage.  This epic is to track the load test instances and bugs coming from the load testing.

**Comment by mitovskaol** [comment]
I noticed that the loaded data does not get indexed by Solr right after the loading, TOB needs to be restarted in order for the indexing to happen.
