### ISSUE TITLE
Merge and deploy current state of TOB v2 to DEV

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#334]

**Comment by WadeBarnes** [comment]
The branch containing TOB v2 was merged and deployed to the BC (https://devex-von-dev.pathfinder.gov.bc.ca/en/home) and Ont (https://ontvon-von-dev.pathfinder.gov.bc.ca/en/home) environments yesterday.

The required v1.1.2 branch of von-network was also merged and deployed to DEV; http://159.89.115.24/

Both environments are updated to the state.
- Clean DB
- Clean Wallet
- Updated Schema-Spy docs.
- Registered with the new ledger instance.

Please note that the UI is currently using demonstration data and has not yet been connected to the new API.

The new API can be seen at https://django-devex-von-dev.pathfinder.gov.bc.ca/api/v1/ and https://django-ontvon-von-dev.pathfinder.gov.bc.ca/api/v1/

Nick confirmed loading credentials through the API worked.
