### ISSUE TITLE
Update OpenShift Apps to use VON-X 1.6 and hence - the SQLLite Wallet - removing the Enterprise Wallet

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#390]
When VON-X 1.6 is available, deploy it to OpenShift for the apps that need it (BC TOB, Ont TOB, BC Reg). In doing that, the Postgres wallet previously used will have to removed and replaced with a persisted SQLLite wallet.

**Comment by WadeBarnes** [comment]
This will require a full wallet and ledger reset for all affected environments.
- TOB (VON, BC, ONT)
- Permitify
- BC Registries Agent

Since we're resetting the ledger it may be a good time to switch the ledger back to use standard ports now that they are open for outbound traffic in the OpenShift environment.

**Comment by WadeBarnes** [comment]
The following components are using the Enterprise Wallet:
* TOB (VON, BC, ONT)
* Permitify

TOB needs to have it's sqlite wallet storage restored, it was removed in favor of the EW.

Permitify still has it's sqlite wallet storage being provisioned.

**Comment by WadeBarnes** [comment]
Storage requirements based on loading test data:

Indy Wallet for Issuer (Registries Agents):
* DEV/TEST: 1GB
* PROD: 1GB

Event processor DB (Registries Agents)
* DEV/TEST: 15GB
* PROD: 25 GB

Mara DB (Registries Agents)
* DEV/TEST: 1GB
* PROD: 1GB

Indy Wallet for TOB Holder (TOB Instances)
* DEV/TEST: 60GB
* PROD: 90GB

TOB DB (TOB Instances)
* DEV/TEST: 10GB
* PROD: 15GB

SOLR (TOB Instances)
* DEV/TEST: 120GB
* PROD: 180GB

**Comment by WadeBarnes** [comment]
Updated build and deployment configurations to support Indy 1.6.  Update the PVC allocations based on the numbers from the test results.

**Comment by WadeBarnes** [comment]
The DEV environments have been switched over.  I'm the process of migrating the Ontario TEST environments over.  BC's TOB Demo environment is waiting on updates to permitify.

**Comment by WadeBarnes** [comment]
Ontario TEST environments have been migrated.
