### ISSUE TITLE
Survey exposed API and determine what needs to be locked down

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#400]
Review the REST API for TheOrgBook and determine what is OK to be open (Open Data) and what needs to be locked down - e.g. the issuance of credentials. 

Once defined - document the items to be locked down and add a ticket to make it so.

**Comment by nrempel** [comment]
@swcurran are there specific rules around what can be shown or is all of the data "public"?

If that is the case, I will move forward with the assumption that all read-online endpoints will be left open and any "indy" related endpoints (write) will be locked down.

**Comment by cywolf** [comment]
@nrempel  Yes, apart from /indy/status which is just for debugging info.

**Comment by nrempel** [comment]
Ok, I'll move this to in-review then

**Comment by WadeBarnes** [comment]
We currently protect the search and data endpoints behind the client which requires authentication.  There is a direct route to the API, but it only exposes the `api/v2/indy/*` endpoints.  This new configuration is being rolled out as environments that will need the tightened security are updated.

**Comment by nrempel** [comment]
@WadeBarnes @swcurran I'm moving this task to done.

If we still have concerns around this, let's open up some more granular issues.
