### ISSUE TITLE
Exception from TOB when registering issuer with VON-X having name longer then 30 chars

### ISSUE THREAD

**Issue by weiiv** [bcgov/TheOrgBook#403]

**Comment by swcurran** [comment]
@weiiv - can you add any docs to this?  Stack trace, etc?

Over to you, @nrempel.

**Comment by weiiv** [comment]
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:266 | indy_close_wallet: >>> handle: 5
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:270 | indy_close_wallet: entities >>> handle: 5
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:284 | indy_close_wallet: <<< res: Success
tob-api_1        |  INFO|indy::commands                |                src/commands/mod.rs:122 | WalletCommand command received
tob-api_1        | DEBUG|indy::commands::wallet        |             src/commands/wallet.rs:171 | close >>> handle: 5
tob-api_1        | TRACE|indy::services::wallet        |         src/services/wallet/mod.rs:315 | close >>> handle: 5
tob-api_1        |  INFO|indy::services::wallet::virtualid|   src/services/wallet/virtualid.rs:268 | wallet.close >>>
tob-api_1        | TRACE|indy::services::wallet        |         src/services/wallet/mod.rs:322 | close <<< res: ()
tob-api_1        | DEBUG|indy::commands::wallet        |             src/commands/wallet.rs:175 | close << res: ()
tob-api_1        | TRACE|indy::api::wallet             |                  src/api/wallet.rs:277 | indy_close_wallet:
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:200 | indy_close_pool_ledger: >>> handle: 2
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:204 | indy_close_pool_ledger: entities >>> handle: 2
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:218 | indy_close_pool_ledger: <<< res: Success
tob-api_1        |  INFO|indy::commands                |                src/commands/mod.rs:114 | PoolCommand command received
tob-api_1        | DEBUG|indy::commands::pool          |               src/commands/pool.rs:182 | close >>> handle: 2
tob-api_1        | TRACE|indy::services::pool          |           src/services/pool/mod.rs:294 | zmq poll 1
tob-api_1        | TRACE|indy::services::pool          |           src/services/pool/mod.rs:311 | cmd [[101, 120, 105, 116], [8, 0, 0, 0]]
tob-api_1        | TRACE|indy::services::pool          |           src/services/pool/mod.rs:245 | process_actions - Pool work terminated
tob-api_1        |  INFO|indy::commands                |                src/commands/mod.rs:114 | PoolCommand command received
tob-api_1        | TRACE|indy::api::pool               |                    src/api/pool.rs:211 | indy_close_pool_ledger:
tob-api_1        | DEBUG 2018-08-17 01:32:56,185 auth 150 140419240208128 Creating user for DID 'did:sov:29wkixvUJPi3VhawpPihKR' ...
tob-api_1        | ERROR 2018-08-17 01:32:56,189 exception 150 140419240208128 Internal Server Error: /api/v2/indy/register-issuer
tob-api_1        | Traceback (most recent call last):
tob-api_1        |   File "/home/indy/api/auth.py", line 26, in create_issuer_user
tob-api_1        |     user = User.objects.get(DID=issuer_did)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
tob-api_1        |     return getattr(self.get_queryset(), name)(*args, **kwargs)
tob-api_1        |   File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
tob-api_1        |     self.model._meta.object_name
tob-api_1        | api.models.User.DoesNotExist: User matching query does not exist.

**Comment by nrempel** [comment]
This is coming from Django's default auth model that we are extending:

https://github.com/bcgov/TheOrgBook/blob/master/tob-api/api/models/User.py#L2

https://github.com/bcgov/TheOrgBook/blob/master/tob-api/api/migrations/0001_initial.py#L30

I will add and use an additional custom field instead of overloading `last_name`

**Comment by nrempel** [comment]
https://github.com/bcgov/TheOrgBook/pull/409
