### ISSUE TITLE
Hard coded restrictions make issuer registration hard

### ISSUE THREAD

**Issue by weiiv** [bcgov/TheOrgBook#404]
SUPPORTED_MODELS_MAPPING = {
    "name": Name,
    "address": Address,
    "person": Person,
    "contact": Contact,
    "category": Category,
}

SUPPORTED_CATEGORIES = ["topic_status", "topic_type"]

* TODO: Allow issuer to dynamically register topic types
* Currently we only support 2 topic types. We only understand
* a predefined relationship: incorporation --< doing_business_as
SUPPORTED_TOPIC_TYPES = ["incorporation", "doing_business_as", "registration"]

**Comment by swcurran** [comment]
@weiiv / @nrempel - updated the description and assigned this to Nick.  Does this need to be done now, has it been done, or do we put this to backlog to do in the future?  Up to y'all to decide - I'm not sure of the status.

Thanks

**Comment by nrempel** [comment]
This is tracked in #408

This will need to be updated as part of the changes to search/api response data which is next up on my list of to-dos
