### ISSUE TITLE
Provide TOB URL for an organization to a Verifier - predictable or Credentials-based

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#414]
We would like a Verifier to have access to the URL in the TOB for the organization being verified. We have two ways we might be able to provide that:

1. We're in the process of making the page for an organization include the "source_id" - e.g. the key from source of the foundational credential for the entity. Assuming that goes through, the Verifier can construct the URL by adding the source_id, which it can get from the proof it receives, and to a fixed URL.  If this is used, there needs to be an API that provides the Verifier with the fixed part of the URL
1. Alternatively, if we can't construct the URL, another idea we've had is that when each new organization is added to TOB. TOB issues to itself a Credential that contains the source_id for the organization (linking the Credential to the organization). That would allow Verifiers to construct a Proof Request that included TOB's URL for the organization.

Given our current direction, the first suggestion is the most likely to be implemented, but documenting both should our URL scheme for organizations change.

**Comment by jljordan42** [comment]
@cywolf I think this is done?
{URL}/organization/{registration id} works I think?

**Comment by cywolf** [comment]
@jljordan42 Yes, that's done now
