### ISSUE TITLE
TOB Web UI search result navigation not working

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/TheOrgBook#416]
Steps to reproduce:
 - search for business name that returns more than 10 results , i.e. "INC"
 - click the Next page button
 - nothing happens.

**Comment by nrempel** [comment]
re-opening so it's visible on zenhub

**Comment by nrempel** [comment]
Updated a couple references to resolve this issue:

https://github.com/bcgov/TheOrgBook/pull/424
