### ISSUE TITLE
Indy-SDK - specify which tags to create per credential

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#427]
Look into how the SDK tags credentials, and see if it's an option to specify which tags to create (or not)

Potential SDK update

**Comment by swcurran** [comment]
Opened JIRA ticket [IS-914](https://jira.hyperledger.org/projects/IS/issues/IS-914) against the Indy-SDK to request the addition of an option to NOT autocreated a tag for every claim in a credential.

Will update this when that ticket completes.
