### ISSUE TITLE
Add API basic auth for use prior to the official launch

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#437]
We want to be able to load the full set of credentials from the UAT and Production BC Reg databases. When we first do that, we want to block access to the data through the use of a hardcoded userID/password credential on the API.  We don't need a general users support - just a single user and password that we can share with anyone we want to allow to see the application while we're in stealth mode.

When adding Basic Auth was first tried with the application, it didn't play well with the BC Reg integration and so was simply turned off to enable further testing.  With a full database load pending, we will need this in place.

Please experiment with local instances of the components and Docker and try to get a working basic authentication solution that meets our temporary needs.

**Comment by WadeBarnes** [comment]
For a starter on basic auth, have a look at what I did for #338. It's all controlled via env variables to turn on/off at the moment.
