### ISSUE TITLE
Update UI to understand graph-like nature of relationships

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#440]
Currently the UI is structured in such a way that an organization should have a parent and children.

To fit this model, currently we are issuing a `relationship` credentials only on the "parent" of the relationship – in other words, the "owner" of the relationship. i.e., An incorporation topic _has_ doing business as names so the credential for the relationship is issued to the incorporation topic.

In the reality, the data is not hierarchal.

Any topic can have many related topics (relationships that it owns) but it can also be related to other topics which own relationships to it.

We should update the UI to support such a paradigm.

**Comment by swcurran** [comment]
Closing this issue until there is a general review of OrgBook BC's UI. If this makes sense, it will be chosen for implementation at that time.
