### ISSUE TITLE
Implement an asynchronous job queue and move credential processing to worker queue

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#453]
@WadeBarnes just tagging us here to track progress on this.

**Comment by WadeBarnes** [comment]
We've measured a ~12% increase in performance implementing the asynchronous job queue thus far.  However that process is following the credentials being saved into the wallet which appears to be a bit of a bottle neck of it's own when its called upon to store and enterprise volume of information.  Once we have recreated/refactored our enterprise wallet implementation we are likely to see additional performance gains using this approach.
