### ISSUE TITLE
Updates to the TOB Credential Screen

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#466]
Here are the ideas I have for the Credentials screen. Others (@jljordan42) should add/modify this and then assign the task to @cywolf :

1. Perform the Proof Request automatically on loading - because...
1. At the top show the Credential Type, Issuer, and name of Topic to which the Credential is associated (e.g. Legal Entity or DBA, etc.)
1. Show an icon that indicates Verification of the credential - e.g. "Proof of Claims: " and a large green check or red x depending on status.
1. Show credential status information - Date Effective, Date Received by TOB, Date Revoked.
1. If date revoked is set, include link to "Active version of Credential"
1. Section "Claims Proven and Verified" and list of fields in the Proof Request
1. Section Credential and Proof Details - expandable section, initially collapsed, with "What is this?" information link
1. On expansion show: Schema in a section and below that "Cryptographic Proof Data" with a "What is this?" link.

Content for the two "What is this?" links to be provided.

**Comment by cywolf** [comment]
Still need "What's this?" text for the two links, @swcurran @jljordan42
