### ISSUE TITLE
BC Reg X - Credential Dates displayed in TOB

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#479]
Investigate which credential dates are displayed in TOB and where they come from.

(Seems like "current timestamp" is displayed?)

**Comment by ianco** [comment]
Confirmed dates are all displaying correctly:
- Dates in BC Reg database are PST
- Convert to UTC when generating credentials
- When displaying in TOB, confirmed the original PST datetimes are displayed

**Comment by swcurran** [comment]
It should be "When displaying in TOB, the browser location timezone should
be presented".

I assume that is what you meant, right?

**Comment by ianco** [comment]
Yes Stephen that's right, I just tested it out.
