### ISSUE TITLE
Implement ability to re-run credential processor for all credentials after new config has been submitted

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#483]

**Comment by nrempel** [comment]
This has been added as a django management command.

This can be run in the local docker-compose environment by running `./manage django reprocess_credentials`

It deletes all "search" records and reprocesses the existing credentials and creates new records using the latest processor config from the issuer.

This can be used, for example, if we wanted to add categories (for extra UI stuff) to all credentials. Using this command, this could be done without re-issuing credentials.

cc: @mitovskaol @weiiv

**Comment by weiiv** [comment]
Thanks Nick 😊

**Comment by WadeBarnes** [comment]
The command crashes or get killed when processing large numbers of records.

**Comment by swcurran** [comment]
@nrempel - back to you to put a governor on it?  Do you know what a "governor" is?

**Comment by nrempel** [comment]
I'm not familiar with that term. I'm assuming it is a software pattern?

I'll take a look.

**Comment by nrempel** [comment]
@WadeBarnes Do you have any extra logs or information from when the crash occurred?

**Comment by cywolf** [comment]
It needs some changes to work with the optimizations for the real time Solr indexing. I have updates for that in progress.

**Comment by WadeBarnes** [comment]
I don't have any logs it crashed silently.

**Comment by nrempel** [comment]
@cywolf did those changes go in to fix this?

**Comment by cywolf** [comment]
@nrempel Yes, it should be working fine now

**Comment by WadeBarnes** [comment]
@nrempel, was this retested on a large set of credentials?

**Comment by nrempel** [comment]
No, I haven't tested Andrew's changes. Should be safe to run a test on DEV if there is enough data in there. If you're OK with that I can run a test.

**Comment by WadeBarnes** [comment]
@nrempel, There is enough data in `devex-von-bc-tob-dev`.  Go for it.

**Comment by nrempel** [comment]
This was having issues eating up too much memory and getting killed by openshift.

I've worked around this by using https://docs.djangoproject.com/en/2.1/ref/models/querysets/#iterator since the results set of credentials is so large. This performs a little slower but disables caching which appears to fix the problem.
