### ISSUE TITLE
Add place and provide instructions for copy of Ontario JSON credentials into Prod Environment

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#496]
Ontario has a JSON file with 7.5M credentials ready to be loaded. Rather than having Onbis-x pod accessing those records across the internet, we'd like to compress them, push them into persistent storage on the Prod environment and then uncompress them so that local file can be the source of the loading.

Tasks:
- [x] Create the persistent storage for this
  - A 100 GB persistent volume has been provisioned and mounted to `/tmp` on the `onbis-x-agent` container.
- [x] Provide Ivan with access to the environment
- [x] Provide instructions on how to upload the compressed file and unzip.

Please check with Ivan on any other details needed.

Thanks!

**Comment by WadeBarnes** [comment]
To copy the compressed json file to the persistent volume and extract it.  Run the following commands from your workstation:

1) Determine the name of the active agent pod.  In this example it is `onbis-x-agent-2-7t45t`:
```
Wade@hvWin10x64 MINGW64 /c/onbis-x/testdata (master)
$ oc get pods -n ontvon-von-ont-registries-agent-prod

NAME                    READY     STATUS    RESTARTS   AGE
onbis-x-agent-2-7t45t   1/1       Running   0          2m
onbis-x-proxy-1-29s5q   1/1       Running   0          30m
```
2) Copy the compressed file to the `/tmp` folder (where the persistent volume is mounted):
```
Wade@hvWin10x64 MINGW64 /c/onbis-x/testdata (master)
$ oc cp -n ontvon-von-ont-registries-agent-prod ./test.json.gz onbis-x-agent-2-7t45t:/tmp
```
3) Extract the archive:
```
Wade@hvWin10x64 MINGW64 /c/onbis-x/testdata (master)
$ oc exec -n ontvon-von-ont-registries-agent-prod onbis-x-agent-2-7t45t -- bash -c 'gunzip -c /tmp/test.json.gz > /tmp/test.json'
```
