### ISSUE TITLE
Document script to create DID from seed

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#500]

**Comment by ianco** [comment]
We can do this manually using CLI, as per:

https://github.com/bcgov/TheOrgBook/blob/master/docs/CLI-README.md

**Comment by swcurran** [comment]
@mitovskaol, @ianco, @WadeBarnes - updated the CLI readme with the directions on creating the seeds and DIDs for putting onto Sovrin for Ontario and others. 

See section in this doc: https://github.com/bcgov/TheOrgBook/blob/master/docs/CLI-README.md

Olena - that can be done at any time, so feel free to start that process with Sovrin.
