### ISSUE TITLE
Connecting to the STN and SLN

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#517]
Currently, our instances of TOB and BCREGX talk to the Digital Ocean-based ledger(s).  For the RealProd, we'll be using the SLN.  The DO-based ledgers have an associated web service that will not be there for RealProd.  How do we do this?

Things to consider:

* The DIDs for BCRegX and TOB will already be on the ledger - no need to create them.
* When BCRegX creates new entities - schema, CredDefs - we need to use the BCRegX DID for that
  * Until SLN/STN, we have always had access to a known Trustee seed/DID that we have always used. That will not work

In theory, we should just be able to use the genesis files for doing this, but that's probably not going to work directly.

You may need help from Wade and Stephen Klump (on what VON Anchor needs for the Trustee/Trust Anchor) for this.

Good luck and godspeed.

**Comment by ianco** [comment]
Updated von-x:

- Added new GENESIS_URL param to specify URL to download genesis file (as opposed to using LEDGER_URL)
- Added new parameter to specify ledger protocol (1.3 for STN)

Also used correct url for STN genesis file (https://raw.githubusercontent.com/sovrin-foundation/sovrin/1.1.50-master/sovrin/pool_transactions_sandbox_genesis)

Von-x still has references to the ledger_url (von-network web server) however I don't think they will ever be used in a production setting.
