### ISSUE TITLE
TheOrgBook Issuer Service: Issue "Proof Receipts"

### ISSUE THREAD

**Issue by jljordan42** [bcgov/TheOrgBook#532]
This is a future feature where a verifier can ask TheOrgBook for a verifiable credential (schema TBD) which will allow the verifier to prove that they asked for a proof (somehow) and from which they can receive the PRI (URL) of the organization they requested the proof for (not sure how we tied this credential to a previous proof request to they can't get a proof request for org X -- and ask for a receipt for org Y)

Being able to get the URL of the org page for an entity might be a nice way to allow third parties to the verifiers to trace back to the source of truth in TheOrgBook

**Comment by swcurran** [comment]
@jljordan42 - I think this one OBE (Overcome By Events).  I'd say we no longer need this with the way that TOB URLs are now formed.  The Verifier can find the URL of the organization by using the ID they receive in the BC Reg (or other foundational credential) Proof.

If you agree, please close this issue.

Thanks!
