### ISSUE TITLE
API Timeout via Swagger UI

### ISSUE THREAD

**Issue by jljordan42** [bcgov/TheOrgBook#558]
![image.png](https://images.zenhubusercontent.com/5849aef8b9dc3c6220233b11/abd2daaf-e6a7-49e3-b4ad-1d6b90610c5c)

**Comment by nrempel** [comment]
New documentation generator is inferring base url incorrectly as internal openshift url.

Solution: add APPLICATION_URL environment variable and set base url explicitly.

**Comment by nrempel** [comment]
@WadeBarnes I have a fix for the missing redirect issue in openshift here: https://github.com/bcgov/TheOrgBook/pull/576

Would you mind reviewing this quickly to ensure there is nothing missing for the OC deployment?
