### ISSUE TITLE
Schema spy error

### ISSUE THREAD

**Issue by DanielaNye** [bcgov/TheOrgBook#560]
Hello, i'm having a problem when running ./manage.sh start.
Below there's a print screen of the issue.

![screenshot from 2018-10-08 15-02-40](https://user-images.githubusercontent.com/35996914/46613754-eca33d80-cb0b-11e8-8e2d-ac3928dc18df.png)

Does anybody knows what's happening?

**Comment by swcurran** [comment]
This is a timing error. Schema Spy is starting up before the database is available and it needs the database to be able to run. Schema Spy is only used for looking at the structure of the database, so it not running will not affect the operation. We have not worked on how to put a delay in it starting so it does not run before the database is available.

Stephen Curran

**Comment by swcurran** [comment]
@DanielaNye - TheOrgBook works fine with Schema Spy not running, so you can just ignore this issue.  If you do want to solve it, suggest that you increase the sleep time in the `docker/docker-compose.yml` file.  Find the Schema Spy section and update the `20` below to a higher value - say 60 - in the following:

```
    command: >
      /bin/sh -c "
        echo sleeping ...;
        sleep 20;
        ./start.sh;"
```

Closing this issue.
