### ISSUE TITLE
Update swagger config with more information

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#566]
We can add description, terms_of_service, contact, license.

Gwells uses the following:

```
description=str("The Well Driller and Pump Installer Registry is a database of qualified well "
                        "drillers and pump installers registered to operate in British Columbia."),
        terms_of_service="http://www2.gov.bc.ca/gov/content?id=D1EE0A405E584363B205CD4353E02C88",
        contact=openapi.Contact(email="groundwater@gov.bc.ca"),
        license=openapi.License(name="Open Government License - British Columbia",
                                url="https://www2.gov.bc.ca/gov/content?id=A519A56BC2BF44E4A008B33FCF527F61"),
```

**Comment by nrempel** [comment]
If someone can provide info for the 4 fields, I can update the config.

**Comment by jljordan42** [comment]
description=str("TheOrgBook is a public searchable directory of digital records for registered businesses in the Province "
                        "of British Columbia. Over time, other government organizations and businesses will also begin to issue"
                        "digital records through TheOrgBook. For example, permits and licenses issued by various government services."),
        terms_of_service="https://www2.gov.bc.ca/gov/content/data/open-data",
        contact=openapi.Contact(email="bcdevexchange@gov.bc.ca"),
        license=openapi.License(name="Open Government License - British Columbia",
                                url="https://www2.gov.bc.ca/gov/content/data/open-data/api-terms-of-use-for-ogl-information),
