### ISSUE TITLE
Add rich content previews

### ISSUE THREAD

**Issue by nrempel** [bcgov/TheOrgBook#567]
http://ogp.me
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html

**Comment by swcurran** [comment]
@nrempel - what is this?  Sounds cool, but I don't connect the title with the links.

**Comment by nrempel** [comment]
@swcurran ah, this was so that links to TheOrgBook would expand in slack. It could expand with an image and some meta data about the corporation. Slack, iMessage, and other services will read the data to expand a preview

**Comment by swcurran** [comment]
@cywolf - are you planning to work on this?  I heard a rumour about that.  If not, please unassign from you and move to "Backlog".

Thanks
