### ISSUE TITLE
Errors posting credentials when wallet db is restarted

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/TheOrgBook#571]
Steps to reproduce:
- Starting with a running/working TOB application, ensure it is receiving credentials without error by posting some credentials.
- Restart the wallet-db container.
- Once the container has restarted completely, post some more credentials.

Observed behavior:
- The error, listed below, occurs until the django container (tob-api) is restarted and establishes a new connection with the wallet database.

Expected behavior:
- The error not occur.
- The application not rely on a permanent, persistent connection to the wallet database.

```
INFO 2018-10-10 13:12:00,069 base 1 140031830255360 _BaseAnchor.get_cred_def: got cred def for EyrfRZ4Rz3LWvzPYe8WbmM:3:CL:41:tag from cache
WARNING 2018-10-10 13:12:00,071 libindy 1 140031830255360 _do_call: Function indy_prover_store_credential returned error 112
ERROR 2018-10-10 13:12:00,071 service 1 140031830255360 Exception while handling request:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/common/service.py", line 255, in _handle_message
    reply = await self._service_request(request)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/indy/service.py", line 1190, in _service_request
    request.holder_id, request.credential)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/vonx/indy/service.py", line 810, in _store_credential
    json.dumps(credential.cred_req_metadata),
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/von_anchor/anchor/holder_prover.py", line 616, in store_cred
    rrdef_json)
  File "/home/indy/.pyenv/versions/3.6.3/lib/python3.6/site-packages/indy/anoncreds.py", line 627, in prover_store_credential
    prover_store_credential.cb)
indy.error.IndyError: ErrorCode.CommonInvalidState
WARNING 2018-10-10 13:12:00,074 views 1 140032298075904 <<< Store credential: 0.07383375335484743
```

**Comment by WadeBarnes** [comment]
@cywolf, @ianco, I'm not sure whether this is best handled at the von-x level or at the indy-sdk level inside the postgres wallet implementation.  I'll leave it to you 2 to discuss.

**Comment by WadeBarnes** [comment]
The BC Registries Agent is affected by the same issue; https://github.com/bcgov/von-bc-registries-agent/issues/68

**Comment by ianco** [comment]
Is this just an issue with the postgres wallet, or is this an issue with all postgres databases?

I suspect it will be an issue with the mara database as well as the event processor database (I haven't built any code to automatically reconnect to the database when it is restarted).

Potentially an issue with TOB search database as well, although I think that database connection is handled by Django.

**Comment by WadeBarnes** [comment]
@ianco, Really only effects the postgres wallet.

- TOB application/search database can be restarted without re-connection issues.  django sees to that.
- The mara and event processor databases can be restarted and the connecting process will reconnect when run again.

Obviously there are database connection errors when processes are trying to connect to the database when it is down.  On the event processor side this surfaces as an error in the scripts that terminate execution.  This is fine, since they will reconnect the next time they are run.

**Comment by ianco** [comment]
I'll take this one and look into an indy-sdk solution (since I'm in the code right now anyways)

**Comment by WadeBarnes** [comment]
This issue also affects the ability to verify existing credentials.
