### ISSUE TITLE
New route configuration for ON TOB

### ISSUE THREAD

**Issue by weiiv** [bcgov/TheOrgBook#593]
Hi Wade,

Per our conversion, please make the following route configuration for Ontario TOB:

PROD:
- www.von.gov.on.ca (main site)
- von.gov.on.ca (redirects to main site)
TEST:
- stage.von.gov.on.ca
DEV:
- dev.von.gov.on.ca

Please also add temporary pathfinder routes to match the current ones.

Thanks,
Ivan

**Comment by WadeBarnes** [comment]
I've updated the following routes;

`ontvon-von-prod`
| Name | URL |
|---|---|
| angular-on-nginx | https://www.von.gov.on.ca |
| angular-on-nginx-tmp | https://ontvon-von-prod.pathfinder.gov.bc.ca  |

`ontvon-von-test`
| Name | URL |
|---|---|
| angular-on-nginx | https://stage.von.gov.on.ca |
| angular-on-nginx-tmp | https://ontvon-von-test.pathfinder.gov.bc.ca  |

`ontvon-von-dev`
| Name | URL |
|---|---|
| angular-on-nginx | https://dev.von.gov.on.ca |
| angular-on-nginx-tmp | https://ontvon-von-dev.pathfinder.gov.bc.ca  |

**Comment by WadeBarnes** [comment]
Confirming with @weiiv what we want to do with the redirect for PROD.  I hoping this can be done a a higher level.  The redirect can't be done at the OpenShift route level, meaning, if it were to be done on the OpenShift side, it would have to be done at a lower level such as in the angular (nginx) container.

**Comment by weiiv** [comment]
Thank you Wade.
