### ISSUE TITLE
Re-Launch Post SLN Upgrade

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#597]
The set of tasks that must be done before we reload prod for the final time.

Assigning to @WadeBarnes to track before planning the reload.

* [ ] Sovrin updates the Live Network

**Comment by WadeBarnes** [comment]
External dependency;
- https://github.com/weiiv/onbis-x/issues/8

**Comment by WadeBarnes** [comment]
Completed Jan 20th
