### ISSUE TITLE
Update Django deployments to latest enterprise wallet image

### ISSUE THREAD

**Issue by cywolf** [bcgov/TheOrgBook#613]
At the moment it appears that postgres wallets will need to be recreated at the same time.

Image: py36-1.6-ew-9, and py36-1.6-ew-9-s2i

Update Environments:
- [x] devex-von-dev
- [x] devex-von-test
- [x] devex-von-bc-tob-dev
- [x] devex-von-bc-tob-test
- [x] devex-von-bc-tob-prod
- [x] ontvon-von-dev
- [x] ontvon-von-test
- [x] ontvon-von-prod

- [x] devex-von-bc-registries-agent-dev
- [x] devex-von-bc-registries-agent-test
- [x] devex-von-bc-registries-agent-prod

- [x] ontvon-von-ont-registries-agent-dev
- [x] ontvon-von-ont-registries-agent-test
- [x] ontvon-von-ont-registries-agent-prod

**Comment by WadeBarnes** [comment]
Configuration and settings updated in the following tickets.  Roll-out started.
- https://github.com/bcgov/TheOrgBook/issues/639
- https://github.com/bcgov/von-bc-registries-agent/issues/76
- https://github.com/weiiv/onbis-x/issues/8

**Comment by WadeBarnes** [comment]
@esune, The only environment to update is the TOB Demo `test` environment.

**Comment by esune** [comment]
TOB Demo `test` environment updated successfully.
