### ISSUE TITLE
Ontario Solr Indexing issues - Real Time Indexing does not seem to pick data updates in TEST

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/TheOrgBook#614]
We noticed that data loaded into the Ontario TEST environment via REST API does not get picked by the Real Time Indexing enabled for Solr in TEST. Manually running rebuildSeachIndex.sh script indexes the loaded data successfully.

This needs to be investigated further to ensure that data updates are indexed successfully after each data load and the Solr indexing process finishes successfully and does not fail.

**Comment by WadeBarnes** [comment]
@cywolf, This is the ticket for the issue we discussed last week.

**Comment by mitovskaol** [comment]
I tested the latest fixes in Ont DEV. A fresh data load has run against an empty database.  Entering the "COMPANY"  in https://ontvon-von-dev.pathfinder.gov.bc.ca  shows 5 results in autocomplete , however, running a search for "COMPANY" returns no results.  Even when picking one of the 5 autocomplete suggestions, it yields "No Results" in search. All 5 records returned by the autocomplete, exist in the database and are active not revoked credentials, so should have been returned by the search engine.

Therefore, it looks like the Autocomplete changes have been successful but Real Time Indexing still does not work.

**Comment by WadeBarnes** [comment]
I had a look.  Autocomplete appears to work, but there are no results returned for search at all.  I rebuild the Solr core and ran the `rebuildSeachIndex.sh` script, but there was no difference in the results.  @cywolf, any thoughts?

**Comment by WadeBarnes** [comment]
The issue was the data itself.  I ran `./reprocessCredentials.sh` and the search results contained the expected results.  @mitovskaol, could you try updating one or more of the records to see if the chnages are picked up?  Also t would be good to try the data load again from the beginning.  You can reset the environment with `openshift/manage` script; `./manage -p ontario -e dev resetDatabase`

**Comment by mitovskaol** [comment]
I updated the record in Ont DEV DB and the change became available in UI shortly, as expected. Will work with Ivan to reset the env and reload the data to test RTI

**Comment by mitovskaol** [comment]
Search results are not showing as expected in DEV. Running a search for an exact match

https://ontvon-von-dev.pathfinder.gov.bc.ca/en/search/name?query=SUPREME%20COUNCIL%20OF%20THE%20THIRTY%20THIRD%20DEGREE%20OF%20THE%20ANCIENT%20AND%20ACCEPTED%20SCOTCH%20RITE%20OF%20FREE%20MASONRY%20OF%20THE%20STATE%20OF%20LOUISIANA

returns 14 pages of results. Instead of "AND" logic, it looks like it applies "OR".

**Comment by WadeBarnes** [comment]
@mitovskaol, Your latest update appears to be unrelated to the topic of the ticket; (real-time indexing) RTI not working.  It should be entered as a separate issue.

**Comment by mitovskaol** [comment]
RTI has been tested in Ont Dev and Test and works as expected. The ticket can be closed.
