### ISSUE TITLE
TOB API Swagger Documentation

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#615]

**Comment by ianco** [comment]
Hi Nick, yes, also that any available parameters are documented (for example what are the search options)?  Not sure if this should be part of the Swagger UI, but we need to provide somewhere ...

**Comment by nrempel** [comment]
K 👍🏼

**Comment by nrempel** [comment]
I have a pull request that updates the documentation to include the parameters for the search endpoints. 

https://github.com/bcgov/TheOrgBook/pull/626/files

@cywolf do you mind checking to see if I missed any pertinent parameters? I also wasn't totally clear on the use of each of them so I left the description blank. Would you be able to add a description to each?

**Comment by ianco** [comment]
The query parameters look good (showing up when you click on "try it now") but can we get descriptions for each of the parameters?  For example the parameters for "/search/autocomplete" are "q" and "hl" with no descriptions.

**Comment by ianco** [comment]
... pulling ticket back to "In Progress" to update descriptions for query parameters.

**Comment by nrempel** [comment]
@ianco I'm going to drop off this ticket since Andrew knows the query parameters much better than I do. 

If it's time sensitive, let me know and I can jump back on to do some digging to figure it out and update the docs.
