### ISSUE TITLE
Create GitHub Repo for MOH Von Adaptor

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#617]

**Comment by ianco** [comment]
- name for github repo
- people who require access to github repo
- name for project in OpenShift
- description for project in OpenShift

**Comment by ianco** [comment]
Githib repo name:  VON-ESB-DRS-Agent
People who need access (plus Wade, Ian, Nick, Andrew):
colin.cao@belmar.ca
sandy.j.sethi@pwc.com
daniel.hoang@belmar.ca
Trinity.1.Wolfe@gov.bc.ca

Project name: “ESB DRS Pilot”
Project Description: “Piloting the Dispute Resolution Suite with connections to the OrgBook”

**Comment by WadeBarnes** [comment]
@ianco, The new repository is available at; https://github.com/bcgov/VON-ESB-DRS-Agent

**Comment by WadeBarnes** [comment]
Colin and Daniel have been added to the repo.  Request for OpenShift hosting environments has been submitted.

**Comment by WadeBarnes** [comment]
OpenShift environments have been created:
- l4izby-tools
- l4izby-dev
- l4izby-test
- l4izby-prod

**Comment by WadeBarnes** [comment]
@ianco, please review.  If we've accomplished the items set forth in this ticket, please close.
