### ISSUE TITLE
TOB Need an API to revoke a credential

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#621]
Need the ability to revoke a credential without re-issuing it.

**Comment by cywolf** [comment]
@ianco I realized this is harder than it should be, because it needs to be implemented in the agent as well (basically just forwarding the request with a signature).

**Comment by ianco** [comment]
Basically I need an attribute or status I can include where I am revoking a previously-issued credential, or issuing a credential that I know is already revoked (either because I am generating historical credentials, or because I am "expiring" a credential).

Use cases:
- I am generating a historical credential and I want to issue it with an end date (I already know the end date)
- An address or relationship is now inactive but is not getting replaced (e.g. they move their office or terminate a DBA)

Can I include "end_date" in the credential, and then TOB can have some special-case processing around end dates?

**Comment by ianco** [comment]
I've added "expiry dates" to the address and relationship credentials, so I can re-issue with an "expiry date" if the credential is being expired (for example if a relationship to a DBA is being ended, for example).

Address: address_expiry_date

Relationship:  relationship_expiry_date

These attributes are optional.  If there is no expiry date, the field will not be included in the issued credential.
