### ISSUE TITLE
Update deployment configurations to align with the combined wallet approach

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/TheOrgBook#639]
The latest bcgovimages/von-image set (`-9` series) use a single wallet for all roles if more than one is being used.  Update deployment configurations to align with this new approach.  One key, seed, and did are needed for the wallet credentials.

Refs:
- https://github.com/bcgov/von/issues/106

Update Environments:
- [x] devex-von-dev
- [x] devex-von-test
- [x] devex-von-bc-tob-dev
- [x] devex-von-bc-tob-test
- [x] devex-von-bc-tob-prod
- [x] ontvon-von-dev
- [x] ontvon-von-test
- [x] ontvon-von-prod

**Comment by WadeBarnes** [comment]
Done; https://github.com/bcgov/TheOrgBook/pull/638

**Comment by WadeBarnes** [comment]
@esune, The configurations have already been updated for `devex-von-test`.  So you'll be deploying these configuration updates when you update the TOB/Permitify TEST environment.

**Comment by WadeBarnes** [comment]
The `prod` environments will need to be updated before they are connected to the upgraded SLN environment.

**Comment by WadeBarnes** [comment]
Related Ontario Agent Updates\- https://github.com/weiiv/onbis-x/issues/8

**Comment by WadeBarnes** [comment]
Related BC Agent Updates- https://github.com/bcgov/von-bc-registries-agent/issues/76

**Comment by WadeBarnes** [comment]
@esune, The only environment to update is the TOB Demo `test` environment.

**Comment by esune** [comment]
TOB Demo `test` updated correctly.
