### ISSUE TITLE
Migrate the `devex-von-test` environment to the updated BCovrin TEST ledger

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/TheOrgBook#640]
New ledger address:
- http://138.197.138.255/

**Comment by WadeBarnes** [comment]
@esune, You can do this at the same time you update the configuration for TOB/Permitify.

**Comment by esune** [comment]
#649 prepares for the new TEST deployment, that will happen once ready to deploy permitify TEST and load data.

**Comment by esune** [comment]
Configurations have been updated and changes merged, they will be applied once we deply the new version in test.
