### ISSUE TITLE
Deploy VON-X to OpenShift

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#643]
Deploy initial ESB DRS VON-X implementation to OpenShift DEV and TEST

**Comment by WadeBarnes** [comment]
The build and deployment configurations and settings are complete.

Build configuration have been deployed and tested.  Webhooks have been wired up for the agent and proxy builds.

Deployment configurations have been rolled out to `dev` and `test`, and tested.  We have purposely left `prod` blank.

The agent endpoints are protected by basic auth.  The credentials can be found in the `esbdrs-x-proxy` secrets for those that have the privilege to view them.

Environments:

Tools:
- OpenShift: https://console.pathfinder.gov.bc.ca:8443/console/project/l4izby-tools/overview

DEV:
- OpenShift: https://console.pathfinder.gov.bc.ca:8443/console/project/l4izby-dev/overview
- Url: https://esbdrs-dev.pathfinder.gov.bc.ca 

TEST:
- OpenShift: https://console.pathfinder.gov.bc.ca:8443/console/project/l4izby-test/overview
- Url: https://esbdrs-test.pathfinder.gov.bc.ca

**Comment by WadeBarnes** [comment]
@ianco has been granted access to the OpenShift projects.

**Comment by WadeBarnes** [comment]
Over to @ianco for review.
