### ISSUE TITLE
Update the STRA for TOB

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#656]
Update the STRA for TOB based on feedback from Citizen Services and to include coverage of backup/recovery.  The latest [architectural drawing](https://docs.google.com/document/d/1jHIZpgzCWs-qEneCZGxuzAxdXZtq7AbiMhQ4L4JDrQU/edit?usp=sharing) needs to be updated to reflect current reality.

Note that we **don't** want the document to be posted in Google or github, so we need to collaborate on this using a Word document that we pass around.

Other comment:

> Also, for the Sovrin network, I was unable to include the penetration testing report because it is labelled as confidential. Instead, I referenced the public copy of the Sovrin threat model. - It appears dated, could you check for a more recent copy? 

Specific Requests in the document from Citizen Services include:

> Organizations:
[Explain OCIO process for onboarding/offboarding of organizations]

> Software (VON-X)
[Explain how OCIO ensures that only authorized users can]:
    • Download and install the software on their computers
    • Access the software and enable services for requesting, verifying, and issuing verifiable credentials.

> [Explain each OCIO key management process below]

> [Provide OCIO backup processes for these areas]
    • Source Code and Setup files 
    • Tools Area
    • Dev/Test/Prod Area

> [Explain OCIO process for backing up and protecting the private key]

> Recovery from loss of Private Key
[Explain OCIO process for recovering from loss of private key]

**Comment by swcurran** [comment]
@WadeBarnes - assigning this to you to take an initial cut at the sections for our review only.  We'll take another pass together at this before sending it back to the OCIO.  Document coming to you on another channel.

I'll take a cut at the Architectural Drawing.

@jljordan42 - this will go to you after Wade and I take a shot.  Do you want to include or exclude BC Data Gateway in this document?  We have both versions now - which do we use?

**Comment by WadeBarnes** [comment]
Over the @jljordan42, the updated doc was passed back to @swcurran

**Comment by swcurran** [comment]
@jljordan42 - this is back with me. I'll review what Wade did and then pass it to you.  Updated the diagram as well and will put that into the doc.

**Comment by swcurran** [comment]
You should work on this @jljordan42

**Comment by jljordan42** [comment]
I believe this can be closed now.
