### ISSUE TITLE
TheOrgBook is not showing Expired credentials

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#661]
For example http://localhost:8080/en/organization/BC0093733:

- clicking on "Current" or "Past" in list mode only shows current credentials
- timeline mode shows all credentials

See attached screenshots
![Screen Shot 2018-11-13 at 7.36.07 AM.png](https://images.zenhubusercontent.com/5ae1f0a54b5806bc2bd0c6b2/e5ce1707-bae2-4b1a-86bd-0ef11e7993e9)![Screen Shot 2018-11-13 at 7.35.58 AM.png](https://images.zenhubusercontent.com/5ae1f0a54b5806bc2bd0c6b2/ea47227d-4709-4700-ac81-14c7622b1c78)

**Comment by ianco** [comment]
![Screen Shot 2018-11-13 at 7.36.07 AM.png](https://images.zenhubusercontent.com/5ae1f0a54b5806bc2bd0c6b2/6e668dc2-edd5-4420-a242-9ecd7aeddf5c)

**Comment by cywolf** [comment]
@ianco Yes, that's intentional. The current/past filter refers to active or inactive credentials. It also only shows 'latest' credentials at the moment, meaning the latest effective date in that credential set.
