### ISSUE TITLE
Reload the credentials on the newly upgraded SLN

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#662]
The task to run the reload.  Please assign this task to anyone on the BC Team that needs to do something for the load.  From the Slack convo, it looks like that is just you @WadeBarnes right now, but @ianco or @cywolf might also be needed.

Please wait for the VON_Anchor upgrade from Mr. Klump before doing the reload.  That event will trigger the need for updates from Andrew (von-image) and Ian (verify credential generation and proving still works).

Getting this out the door is a pretty high priority.  That and we're excited to know how fast things load.

**Comment by WadeBarnes** [comment]
Completed Jan 20th
