### ISSUE TITLE
Unable to build on Windows

### ISSUE THREAD

**Issue by adamjbradley** [bcgov/TheOrgBook#690]
s2i.exe and sti.exe both in the path. From a PowerShell CLI launched from within Kitematic on Windows I receive the following error
![image](https://user-images.githubusercontent.com/1193259/49333443-ae596480-f60a-11e8-94ac-453dc5261358.png)

**Comment by adamjbradley** [comment]
I feel as sometimes I'm a warning to others. Working fine now, thanks!

**Comment by swcurran** [comment]
Closing this issue - happy with the resolution.  Friends don't let Friends use Powershell.

:-)
