### ISSUE TITLE
Swagger UI issue

### ISSUE THREAD

**Issue by mitovskaol** [bcgov/TheOrgBook#692]
Swagger adds the port number 8080 to the URL when submitting request to the TOB API. If the TOB API runs on a URL that does not include the port 8080, the submitted requests fail.

Steps to reproduce:
1) Ontario DEV TOB API is available at https://dev.von.gov.on.ca/api/v2/
2) Open Swagger, test the credential/<cred_id>/formatted method.
3) In Google Dev Tools Network, see that the request is sent to https://dev.von.gov.on.ca:8080/api/v2/credential/260/formatted  and never completes
4) The request sent to the correct url manually works
https://dev.von.gov.on.ca/api/v2/credential/260/formatted

**Comment by cywolf** [comment]
This should be fixed now.
