### ISSUE TITLE
The swagger header information for TOB should be instance specific - e.g. different for BC and Ontario

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#703]
The TOB Swagger page header appears to be hard-coded from BC - or at least has not been changed for the Ontario instance.

If not done already, make the page header configurable by TOB instance, and once done, configure the Ontario instances to have an Ontario-centric message in the header.

For Ontario Dev Swagger (URL: https://dev.von.gov.on.ca/api/v2/), the following is currently showing:

![image.png](https://images.zenhubusercontent.com/594c511551aa2c3057829237/001c1109-d937-4765-b1c4-6896c9ea2cdd)

**Comment by swcurran** [comment]
@WadeBarnes - I just noticed that this has not been deployed.  Can you take a look at doing that?

https://www.von.gov.on.ca/api/

Thanks!

**Comment by WadeBarnes** [comment]
Correct, the code that supports overriding the API header documentation has not been deployed to `test` or `prod`.  @weiiv, It's been over a month since the last tob-api (django container) deployments to `test` and `prod`, have you had time to test the latest version to verify whether or not it can be deployed to `prod`?

**Comment by weiiv** [comment]
Wade, Olena is making another change to our TOB, and will be deployed once it’s been approved. The API change will go together.

Thanks,
Ivan

**Comment by swcurran** [comment]
@mitovskaol - see the notes above as to why this was assigned to you. As soon as the new updates to Ontario OrgBook are done, please assign this to Wade to deploy.  It's ready to go, just needs a go ahead to be deployed.
