### ISSUE TITLE
Issue Second Relationship Credential

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#716]
Implement and issue the second "relationship" credential for the Form -> Corp relationship

This will contain the "business name" of the corp as it appears on the firm's legal docs

This will require a change to the Relationship credential to add an additional attribute for the name

**Comment by jljordan42** [comment]
I believe we have an augmentation to this issue where we can provide an indication on the relationship credential page that there is a name mismatch between the firm owner name and the legal name associated to the owner corpnum. This seems like a helpful approach to both the custodians of the data (registries) and the business owners.
