### ISSUE TITLE
Remove Google Analytics and replace with matomo.org

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#747]
Please remove the code that was added to use Google Analytics and replace it with code for mamota.org (formerly piwik).  In doing that, a matomo service will have to be installed on OpenShift to collect the stats and present the data.  A separate task is being created to handle the server setup - this task will be dependent on the completion of that work.

We will still continue to look into BC Gov Analytics capability, as previously mentioned on this ticket. However we understand that it will take some time to get that in place such that we can use it.  For completeness, here is the information we have now about the GDX solution - https://github.com/bcgov/GDX-Analytics.  I'm trying to connect with the GDX team that is driving that project to get guidance and any tokens/config we might need to get started.  The service is based on snowplow - https://snowplowanalytics.com. More details to be added as I learn more from Dan Pollock of the GDX team.

**Comment by esune** [comment]
Completed with von #197
