### ISSUE TITLE
Update the analytics server routes

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/TheOrgBook#757]
We're currently using generic OCP routes for our analytics servers;
- Fathom: https://fathom-proxy-devex-von-prod.pathfinder.gov.bc.ca/
- Matomo: https://matomo-devex-von-prod.pathfinder.gov.bc.ca/

Update the routes once we have registered DNS entries in the `vonx.io` domain for the servers.

New URLs will be:
- Fathom: https://fathom.vonx.io/
- Matomo: https://matomo.vonx.io/

**Comment by WadeBarnes** [comment]
The DNS registration request has been submitted to @jljordan42.

**Comment by WadeBarnes** [comment]
DNS entries have been registered.

**Comment by esune** [comment]
The new routes have been added.
