### ISSUE TITLE
Error 504 Gateway Time-out - Trying to render the Credentials section for Corps with a large number of relationships

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/TheOrgBook#758]
Getting a *Error 504 Gateway Time-out* in the *Credentials* section for;
- https://orgbook.gov.bc.ca/en/organization/BC0928747

The following API call for the Org is the issue;
- https://orgbook.gov.bc.ca/api/topic/703560/credentialset

The corp has a long list of relations;
- https://orgbook.gov.bc.ca/api/v2/topic/703560

The issue does not occur on Corps with a smaller number of relationships.

**Comment by WadeBarnes** [comment]
@ianco, I'm thinking the record limits we placed on the API may be causing the issue.  It's difficult to tell because you see the request in nginx, but there is no sign of it in the API logs afterword.

**Comment by ianco** [comment]
Getting this same issue on my local, I'll dig into the query

**Comment by ianco** [comment]
This is related to the attributes being loaded for each related Topic for each relationship of the selected Topic.

Basically Pattison Inc (BC0928747) has 80+ related companies, and the query is pulling in *all* the attributes related to Pattison for every relationship.  *all* attributes includes all attributes for the Topic and all related relationships, which includes all of the relationships (basically an exponential growth pattern).

I'm not familiar enough with the logic of how these queries are constructed, so have to reassign, I think to @cywolf  but let me know if there is someone else who should look at this ticket.

**Comment by ianco** [comment]
I added an extra filter for the time being (restrict to only fetching attributes from Registration credentials) but needs review.  The query is slightly faster but still very slow, and I'm not sure the fix I made is the correct approach.

**Comment by esune** [comment]
This pull request in indy-catalyst (https://github.com/bcgov/indy-catalyst/pull/339) fixes the issue in the API. However, for this change to work the topic mapping in the services.yml also needs to change ( see [this](https://github.com/bcgov/indy-catalyst-issuer-controller/blob/master/issuer_controller/config/services.yml#L33) ).

Updating the topic mapping will require to re-issue the credentials, so this is why we currently have not ported the change over to TheOrgBook from ICOB.

**Comment by esune** [comment]
@ianco @WadeBarnes what is the recommended course of action here? Asking you guys since you are the people who know and deal the most with re-issuing credentials.

**Comment by swcurran** [comment]
Figure out why the response is slow and make it faster?  :-)

Seriously, I believe that Ian had said something about a slow query that could be addressed. Is that the case here, or is this a condition that must be dealt with?

**Comment by esune** [comment]
@swcurran see [this](https://github.com/bcgov/TheOrgBook/issues/758#issuecomment-541225618). There is a code change we can port over (currently in ICOB), however it will require re-issuing all the credentials since it is a schema change (basically, the `topic_id` needs to be scoped so that it can be filtered upon).

Things *may* work without reissuing the credentials, but right now we would be filtering on `registration` which is pretty generic and may pull in data from other credentials as well (imagine having a couple of different registration credentials for the same topic).

**Comment by swcurran** [comment]
Got it.  I'd say we do nothing about this and move forward with ICOB as quickly as possible.  Is this holding anyone up, or just something we found?

**Comment by esune** [comment]
I don't think it is holding anyone up, but it is definitely causing issues when querying for corps with a large number of relationships/credentials. If we are good with this while we focus on moving to ICOB I think we're good then.

**Comment by esune** [comment]
Moving to done since we decided that are not going to tackle this in the "old" OrgBook.
