### ISSUE TITLE
Why is the trailing slash needed for https://www.orgbook.gov.bc.ca/api

### ISSUE THREAD

**Issue by ianco** [bcgov/TheOrgBook#775]
https://www.orgbook.gov.bc.ca/api/ ... why is the trailing slash needed? is there a way to make https://www.orgbook.gov.bc.ca/api also ok?

**Comment by jljordan42** [comment]
Built von-network and TheOrgBook locally and tested with Safari
a trailing / was *not* required for the URL to successfully resolve to the OpenAPI page. 
I did note a trailing slash was added at some point in the resolution process

**Comment by swcurran** [comment]
Some investigation was done on this and it's not clear at what level of the technical stack this requirement is coming into being. The investigation is not worth it at this time.

**Comment by WadeBarnes** [comment]
The recent changes fixed the issue when running local with Docker.  Once deployed to OpenShift the issues persists.  I’ll have to look more closely at the issue now in the deployment environment.

**Comment by WadeBarnes** [comment]
Updates to the proxy configuration were required; #851

**Comment by WadeBarnes** [comment]
The issue is resolved, although existing clients may still see the issue due to the proxy having issued permanent redirects for previous settings.

To test open an incognito browser window and browser to https://dev.orgbook.gov.bc.ca/api.  You should be redirected to the swagger API page.

**Comment by WadeBarnes** [comment]
@jljordan42, Please test.
