### ISSUE TITLE
storageclass.storage.k8s.io "gluster-file"/"gluster-file-db" not found

### ISSUE THREAD

**Issue by kenhuang** [bcgov/TheOrgBook#789]
Getting `backup-pvc` `wallet-db` `postgresql` storage pending due to these errors, is there any info on how to fix this issue?

```
storageclass.storage.k8s.io "gluster-file" not found
storageclass.storage.k8s.io "gluster-file-db" not found
```
![Screen Shot 2019-05-02 at 9 46 47 AM](https://user-images.githubusercontent.com/205194/57044611-3b3e4200-6cbf-11e9-9b9d-3c6b36bcd5ea.png)
![Screen Shot 2019-05-02 at 9 41 20 AM](https://user-images.githubusercontent.com/205194/57044572-16e26580-6cbf-11e9-823c-81b29bc61c06.png)
![Screen Shot 2019-05-02 at 9 41 08 AM](https://user-images.githubusercontent.com/205194/57044573-177afc00-6cbf-11e9-8737-aec4fb33bf88.png)

**Comment by WadeBarnes** [comment]
@kenhuang, The `gluster-*` storage classes are unique to our BC hosting environment.  You should be able to update your `.param` files to use a blank storage class.  If that does not work, you can removed the line containing the `storageClass` reference from the template.

**Comment by kenhuang** [comment]
thanks! confirm it is work now:)

**Comment by WadeBarnes** [comment]
Closing as resolved.
