### ISSUE TITLE
Provide visibility/access to short-lived credentials

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#814]
Some credentials last a very short time and are not visible on the timeline. For example, in this case, there is a credential in this timeline with a 24 minute lifetime - https://orgbook.gov.bc.ca/en/organization/BC1001845. Currently, the credential is not visible on the non-timeline views (that's a problem) and is only visible on the timeline if you zoom in to the precise hour of the two issuance events.  It takes awhile, and you don't even know you need to do that.  This has been of ongoing concern with the team at BC Registries, as the hidden credentials are known only because they know of the underlying data.

Another example:  "BC1071287 was created via amalgamation and then changed its name 6 minutes later. It has an “Amalgamation” credential for “COMATT ENTERPRISES LTD.” (name not visible ☹) and a “Notice of Alteration” credential for “RISING PHOENIX FITNESS LTD.”. Unfortunately the first credential does not appear until you zoom way in on the timeline.

Please make these changes:

1. On the timeline add a callout - similar to the "Today" one currently displayed - that identifies where invisible (pixel with less than some value) credentials are on the timeline.  Not sure how to or if to show if there are multiple invisible ones at the same place (see idea below as a possible). Ideally, the user would be able to click the callout to drill into the credential without having to zoom to it.  If there were multiple, that would be harder to do without a callout per hidden credential.

2. On the non-timeline views, change the existing "Archived" button to, or add a new button, called "All" that shows all credentials in the timeline.  Since the "Archived" button is not showing any credentials when clicked, I'm not convinced it is doing anything. If not, change the button. If there is a use case for keeping "Archived", add the new "All" button.

For completeness, another suggestion to make it obvious there were hidden credentials was to add to the name of the credential a "(n of m)" phrase either always, or when it made it obvious there were invisible credentials.  That seems unnecessary with the idea of the callout, but could still be useful.

**Comment by swcurran** [comment]
@ianco - not sure if this is for you, Andrew (knows the timeline/list views) or Emilliano.  If this is not a priority, you can unassign it and move it to backlog.

**Comment by swcurran** [comment]
Closed #794 a duplicate of this and put example into the description of this issue.

**Comment by seanadipose** [comment]
#1 is fixed now in commit 3691b8494773314a229f6fb3faa96d343e45f9b6.
Working on item #2

**Comment by seanadipose** [comment]
This is completed in https://github.com/seanadipose/TheOrgBook/tree/timeline-fixes and https://github.com/bcgov/TheOrgBook/tree/short-lived-credentials

**Comment by seanadipose** [comment]
This is completed in https://github.com/seanadipose/TheOrgBook/tree/timeline-fixes and https://github.com/bcgov/TheOrgBook/tree/short-lived-credentials

**Comment by swcurran** [comment]
This work is completed. It is being added to Indy Catalyst as well. Closing.
