### ISSUE TITLE
Activate the "all organizations" instance of OrgBook BC

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#817]
Please make the current prod-tmp instance of OrgBook BC with all organizations the published version, and reload the prod instance with the same data so that it will soon be the live version.

**Comment by WadeBarnes** [comment]
[ ] - Transfer production routes to `prod-tmp`
[ ] - Prep for `prod` data reload
[ ] - Backup primed empty wallet.
[ ] - `prod` data reload
[ ] - Transfer production route to `prod`

**Comment by WadeBarnes** [comment]
We're live again.
