### ISSUE TITLE
Determine how we will write transactions to the Sovrin MainNet

### ISSUE THREAD

**Issue by swcurran** [bcgov/TheOrgBook#839]
Test out the process for preparing signed-by-the-author transactions for a DID, schema and Credential Definition as required by Liquor Licensing Service (LLS).  This includes:

1. Following and updating the Sovrin process documented [here](https://docs.google.com/document/d/1Djr8UEgzAjKNTfRqCIrJGg_SeVGAGSO8JCNiZt5OoWQ/edit?ts=5d681c46).  Please update the document directly with the instructions. Note that the document only covers DIDs and schema, not credential definitions.

1a. In doing so, test out using one ledger to prepare the transactions, and a second ledger to write the documents.

1b. In doing so, capture the wallet used for preparing the transactions, and then use a restored copy of that ledger to attach to the second ledger.

2. Figure out how to use our software (perhaps ACA-Py) to create and capture the transaction for writing a credential definition.

3. Test out exporting the contents of the wallet (using the CLI) and then using import into a new wallet connected to an agent attached to a new ledger.

4. Verify that on the new ledger that you can issue credentials.

5. Confirm with Lynn Bendixsen of Sovrin that our ledger is set up the same as the current Sovrin MainNet.

Please add comments as progress is made so if this is not completed before you go, others can pick up on it.

If you don't have them already, please get the schema and credential definitions from LLS.

**Comment by WadeBarnes** [comment]
Info regarding the process can be found here;
- https://github.com/ianco/sovrin-write-txns
-  https://zoom.us/recording/play/D8WVfMhYakL19PYXoxTBQgBfYMH8bQO372fC75zTJplAycBSj7sTE-fmQy--RFU4?continueMode=true
