### ISSUE TITLE
 "http://localhost:8080/en/home" not working 

### ISSUE THREAD

**Issue by EtricKombat** [bcgov/TheOrgBook#854]
"TheOrgBook"  home page is not running once we open a browser window to http://localhost:8080/en/home

error snapshot :

![nohomepage](https://user-images.githubusercontent.com/33585301/68146616-68b1c400-ff5e-11e9-8cb7-d8c1e3506017.JPG)

## Expected Output:

Once the command **manage start seed=the_org_book_0000000000000000000**  is executed ,the web browser was suppose to bring up (check the snapshot ) the below listed url : 
# URL
http://localhost:8080/en/home

Snapshot of expected output:
![TheOrgBook1](https://user-images.githubusercontent.com/33585301/68230406-f94fd900-001e-11ea-9d47-1792f178e82b.JPG)

**Comment by WadeBarnes** [comment]
@EtricKombat, Were you follow these steps, [Quick Start Guide](https://github.com/bcgov/greenlight/blob/master/docker/VONQuickStartGuide.md#quick-start-guide),when you got the reported error?

**Comment by WadeBarnes** [comment]
Using the latest code and following the instructions to build and start `von-network` and `TheOrgBook` I was able to start the application without issue.

**Comment by swcurran** [comment]
I tried it as well, and all is working as expected. Closing this issue.

@EtricKombat - please let us know if this is still not working, or if you are having other issues.

**Comment by EtricKombat** [comment]
My apologies for delayed response...this didn't happened again
