### ISSUE TITLE
An unknown error occurred.

### ISSUE THREAD

**Issue by zbbgit** [bcgov/TheOrgBook#866]
I am  download the latest code，after run ./manage up  command, there is a mistake on the web-page, as the logs:

tob-web_1      | 192.168.2.173 - - [28/Feb/2020:04:04:14 +0000] "GET /en/home HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36" "-" rt=0.000 urt=- .
tob-web_1      | 2020/02/28 04:04:15 [error] 18#18: *21 open() "/tmp/fathom.js" failed (2: No such file or directory), client: 192.168.2.173, server: localhost, request: "GET /fathom.js HTTP/1.1", host: "192.168.9.144:8080", referrer: "http://192.168.9.144:8080/en/home"

open() "/tmp/fathom.js" failed, how to resolve ？

**Comment by swcurran** [comment]
Odd...i just gave it a try and it works fine. I'm running on Linux, but not much has changed in quite awhile. I gather you are on a Mac?

Did you run `./manage build` before running `./manage up`?

Please check you are following the instructions and make sure your docker environment is setup. I think it is likely something local, I'm afraid.

**Comment by zbbgit** [comment]
> Odd...i just gave it a try and it works fine. I'm running on Linux, but not much has changed in quite awhile. I gather you are on a Mac?
> 
> Did you run `./manage build` before running `./manage up`?
> 
> Please check you are following the instructions and make sure your docker environment is setup. I think it is likely something local, I'm afraid.

Thanks，i forget add parameter to ./manage start command, everything is ok

**Comment by WadeBarnes** [comment]
BTW, you can ignore the errors regarding `fathom`.  It's not wired up for local docker environments.
