### ISSUE TITLE
connect to the wallet-db

### ISSUE THREAD

**Issue by zbbgit** [bcgov/TheOrgBook#869]
I want to connect the wallet-db by Navicat Premium tool, have tried sometimes but failed, anyone who can tell me the information about the database name、user/password.  Thanks.

**Comment by WadeBarnes** [comment]
In a docker instance:
- The database credentials are injected into the wallet-db container here; https://github.com/bcgov/TheOrgBook/blob/master/docker/docker-compose.yml#L203
- The port is mapped to localhost here; https://github.com/bcgov/TheOrgBook/blob/master/docker/docker-compose.yml#L210
- The credentials are defined here; https://github.com/bcgov/TheOrgBook/blob/master/docker/manage#L279

**Comment by WadeBarnes** [comment]
If you are using an instance deployed into OpenShift using our configurations, you'll find the randomly generated credentials in a secret; https://github.com/bcgov/TheOrgBook/blob/master/tob-wallet/openshift/templates/wallet-db-deploy.json#L202

**Comment by zbbgit** [comment]
> In a local docker instance:
> 
> * The database credentials are injected into the wallet-db container here; https://github.com/bcgov/TheOrgBook/blob/master/docker/docker-compose.yml#L203
> * The port is mapped to localhost here; https://github.com/bcgov/TheOrgBook/blob/master/docker/docker-compose.yml#L210
> * The credentials are defined here; https://github.com/bcgov/TheOrgBook/blob/master/docker/manage#L279



  # tob-db
  export POSTGRESQL_DATABASE="THE_ORG_BOOK"
  export POSTGRESQL_USER="DB_USER"
  export POSTGRESQL_PASSWORD="DB_PASSWORD"
  export ENABLE_REALTIME_INDEXING="1"

  # wallet-db
  export WALLET_TYPE="postgres_storage"
  export WALLET_ENCRYPTION_KEY="key"
  export POSTGRESQL_WALLET_HOST="wallet-db"
  export POSTGRESQL_WALLET_PORT="5432"
  export POSTGRESQL_ADMIN_USER="postgres"
  export POSTGRESQL_ADMIN_PASSWORD="mysecretpassword"

According to the reference, i have open the THE_ORG_BOOK by client tool（DB_USER/DB_PASSWORD）, but show two database: THE_ORG_BOOK and postgres. so my question is ：
1、When operate the greenLight to  getting permit or license， i can see  new data in THE_ORG_BOOK， but  postgres is still null， no table at all.
2、The postgres belong to wallet-db ?   if not ，how to get more information about the wallet

**Comment by WadeBarnes** [comment]
You know you are looking at the correct database when you see the following tables;
```
                List of relations
 Schema |      Name      | Type  |     Owner     
--------+----------------+-------+---------------
 public | items          | table | User_5fVmWxzJ
 public | metadata       | table | User_5fVmWxzJ
 public | tags_encrypted | table | User_5fVmWxzJ
 public | tags_plaintext | table | User_5fVmWxzJ
```

**Comment by WadeBarnes** [comment]
BTW, The records in the wallet are encrypted.

**Comment by swcurran** [comment]
Closing issue - let us know if more information is needed.
