### ISSUE TITLE
 ERROR: pull access denied for schema-spy

### ISSUE THREAD

**Issue by EtricKombat** [bcgov/TheOrgBook#888]
Hi Team,

While trying to bring up TheOrgBook (./manage start ) getting this below listed error.
Any idea on how to resolve this?

        sudo ./TheOrgBook/docker/manage start seed=the_org_book_0000000000000000000

        WARNING: The INDY_WALLET_DID variable is not set. Defaulting to a blank string.
        Pulling schema-spy (schema-spy:)...
        ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

        Continue with the new image? [yN]y
        Pulling schema-spy (schema-spy:)...
        ERROR: pull access denied for schema-spy, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Snapshot:

![TheOrgBook_issue](https://user-images.githubusercontent.com/33585301/83800604-4a16d580-a6c5-11ea-876f-7f278459a13f.JPG)

**Comment by swcurran** [comment]
Could you try doing a `./manage build`?  I'm thinking that's not been run yet, or at least the images were deleted since it was last run.

**Comment by EtricKombat** [comment]
closing this as this as
